// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  hero: dynamic(() => import("./Hero")),
  image_only: dynamic(() => import("./ImageOnly")),
  post_header: dynamic(() => import("./PostHeader")),
  rich_text: dynamic(() => import("./RichText")),
  text_blog: dynamic(() => import("./TextBlog")),
};
