// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_post_header: dynamic(() => import("./BlogPostHeader")),
  image_block: dynamic(() => import("./ImageBlock")),
  table_block: dynamic(() => import("./TableBlock")),
  text_block: dynamic(() => import("./TextBlock")),
};
